#the files that are used for the system tests are stored on a MPI datashared and the download links as well as the directory and file names are stored here
system_tests:
  quicktests: https://datashare.biochem.mpg.de/s/UbF6TdVGAsYuNrR