name: nbdev unit tests
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install with dependencies
        shell: bash -l {0}
        run: |
          pip install -e ./directlfq[development]
      - uses: fastai/workflows/nbdev-ci@master
