on: 
   push:
   pull_request:
   workflow_dispatch:

name: Quick tests based on default installation

jobs:
  loose_installation:
    name: Test loose pip installation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Test pip installation with all loose dependencies
        shell: bash -l {0}
        run: |
          cd misc
          . ./loose_pip_install.sh

      # - uses: yaananth/run-notebook@v2
      #   env:
      #     RUNNER: ${{ toJson(runner) }}
      #     SECRETS: ${{ toJson(secrets) }}
      #     GITHUB: ${{ toJson(github) }}
      #   with:
      #     notebook: "tests/quicktests/run_pipeline_w_different_input_formats.ipynb"
      #     params: "PATHTOPARAMS.json"
      #     isReport: False
      #     poll: True
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: output
      #     path: ${{ RUNNER.temp }}/nb-runner
      #   env:
      #     RUNNER: ${{ toJson(runner) }}
  
      - name: Unittests
        shell: bash -l {0}
        run: |
          cd tests
          . ./run_quicktests.sh
